Updated script files to use env vars and added help blocks to each.

diff --git a/beagle_board/scripts/bb_backup_system_files b/beagle_board/scripts/bb_backup_system_files
--- a/beagle_board/scripts/bb_backup_system_files
+++ b/beagle_board/scripts/bb_backup_system_files
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+# Script written to monitor and control the DATA robot by Sawyer Larkin
+
+NAME=`basename $0`
+
+display_usage ()
+{
+  echo "Usage: $NAME [options]"  1>&2
+  echo "" 1>&2
+  echo "Copies relevant system files that I have updated into this repository for backup." 1>&2
+  echo "" 1>&2
+  echo "  -h Print this message" 1>&2
+	exit 1	
+}
+
+while getopts "h" opt
+do
+  case ${opt} in
+    h )
+      display_usage
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
+
 cp /etc/wpa_supplicant.conf ~/beagleboard_navstack/beagle_board/system_files/etc/
 cp /etc/connman/main.conf   ~/beagleboard_navstack/beagle_board/system_files/etc/connnman/
 cp /etc/network/interfaces  ~/beagleboard_navstack/beagle_board/system_files/etc/network/
diff --git a/beagle_board/scripts/bb_trainer_off b/beagle_board/scripts/bb_trainer_off
--- a/beagle_board/scripts/bb_trainer_off
+++ b/beagle_board/scripts/bb_trainer_off
@@ -1,6 +1,36 @@
 #!/bin/bash
 
-#echo low > /sys/class/gpio/gpio162/direction
+# Script written to monitor and control the DATA robot by Sawyer Larkin
+
+NAME=`basename $0`
+
+display_usage ()
+{
+  echo "Usage: $NAME [options]"  1>&2
+  echo "" 1>&2
+  echo "Powers off the BeagleBoard Trainer Board on the DATA robot, if it's currently powered." 1>&2
+  echo "" 1>&2
+  echo "  -h Print this message" 1>&2
+	exit 1	
+}
+
+while getopts "h" opt
+do
+  case ${opt} in
+    h )
+      display_usage
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
 
 # Chip gpio_162, linux gpio_130
 POWER_IO=130
diff --git a/beagle_board/scripts/bb_trainer_on b/beagle_board/scripts/bb_trainer_on
--- a/beagle_board/scripts/bb_trainer_on
+++ b/beagle_board/scripts/bb_trainer_on
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+# Script written to monitor and control the DATA robot by Sawyer Larkin
+
+NAME=`basename $0`
+
+display_usage ()
+{
+  echo "Usage: $NAME [options]"  1>&2
+  echo "" 1>&2
+  echo "Powers on the BeagleBoard Trainer Board on the DATA robot, if it's not already powered." 1>&2
+  echo "" 1>&2
+  echo "  -h Print this message" 1>&2
+	exit 1	
+}
+
+while getopts "h" opt
+do
+  case ${opt} in
+    h )
+      display_usage
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
+
 # Chip gpio_162, linux gpio_130
 POWER_IO=130
 POWER_GPIO=gpio$POWER_IO
diff --git a/beagle_board/scripts/bb_trainer_reset b/beagle_board/scripts/bb_trainer_reset
--- a/beagle_board/scripts/bb_trainer_reset
+++ b/beagle_board/scripts/bb_trainer_reset
@@ -1,5 +1,35 @@
 #!/bin/bash
 
+# Script written to monitor and control the DATA robot by Sawyer Larkin
+
+display_usage ()
+{
+  echo "Usage: $NAME [options]"  1>&2
+  echo "" 1>&2
+  echo "Resets the BeagleBoard Trainer Board on the DATA robot." 1>&2
+  echo "" 1>&2
+  echo "  -h Print this message" 1>&2
+  exit 1
+}
+
+while getopts "h" opt
+do
+  case ${opt} in
+    h )
+      display_usage
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
+
 bb_trainer_off
 sleep 0.05
 bb_trainer_on
diff --git a/beagle_board/scripts/data_read_time b/beagle_board/scripts/data_read_time
--- a/beagle_board/scripts/data_read_time
+++ b/beagle_board/scripts/data_read_time
@@ -2,11 +2,99 @@
 
 # Script written to monitor and control the DATA robot by Sawyer Larkin
 
-I2C_BUS=1
-I2C_BOARD=6
+NAME=`basename $0`
 
-while [ true ]
+display_usage() 
+{ 
+  echo "Usage: $NAME [options]"  1>&2
+  echo "" 1>&2
+  echo "Reads the current value of the system timer on the BB Trainer via I2C." 1>&2
+  echo "If count or single options are not specified the timer will be continuously polled." 1>&2
+  echo "If no I2C setup options are specified they will attempt to be set" 1>&2
+  echo "by environment variables:" 1>&2
+  echo "DATA_BASE_I2C_BUS and DATA_BB_TRAINER_I2C_ADDR" 1>&2
+  echo "" 1>&2
+  echo "  -a=ADDRESS  I2C board address to be used" 1>&2
+  echo "  -b=BUS      I2C bus number to be used" 1>&2
+  echo "  -c=COUNT    Number of times to read and print the time value" 1>&2
+  echo "  -h          Print this message" 1>&2
+  echo "  -s          Read the encoders a single time" 1>&2
+  echo "  -v          Verbose, print various config parameters" 1>&2
+	exit 1
+}
+
+INVALID=INVALID
+VERBOSE=0
+COUNT=-1
+
+# Assign I2C parameters from environment vars if possible
+I2C_BUS=${DATA_BASE_I2C_BUS:-$INVALID}
+I2C_BOARD=${DATA_BB_TRAINER_I2C_ADDR:-$INVALID}
+
+while getopts "a:b:c:hsv" opt
+do
+  case ${opt} in
+    a )
+      I2C_BOARD=$OPTARG
+      ;;
+    b )
+      I2C_BUS=$OPTARG
+      ;;
+    c )
+      COUNT=$OPTARG
+      ;;
+    h )
+      display_usage
+      exit 0
+      ;;
+    s )
+      COUNT=1
+      ;;
+    v )
+      VERBOSE=1
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
+
+if ! [[ $I2C_BUS =~ ^[0-9xX]+$ ]]
+then
+  echo "No valid I2C bus specified!" 1>&2
+  echo "I2C Bus Number:    $I2C_BUS" 1>&2
+  echo "I2C Board Address: $I2C_BOARD" 1>&2
+	display_usage
+fi
+
+if ! [[ $I2C_BOARD =~ ^[0-9xX]+$ ]]
+then
+  echo "No valid I2C board address specified!" 1>&2
+  echo "I2C Bus Number:    $I2C_BUS" 1>&2
+  echo "I2C Board Address: $I2C_BOARD" 1>&2
+	display_usage
+fi
+
+if [[ VERBOSE -ne 0 ]]
+then
+  echo "I2C Bus Number:    $I2C_BUS"
+  echo "I2C Board Address: $I2C_BOARD"
+  echo
+fi
+
+while [[ $COUNT -ne 0 ]]
 do
   echo -n "System Timer: "
   i2cget -y $I2C_BUS $I2C_BOARD 0xE w
+
+  if [[ $COUNT -gt 0 ]]
+  then
+    COUNT=$((COUNT - 1))
+  fi
 done
diff --git a/beagle_board/scripts/front_shell_program b/beagle_board/scripts/front_shell_program
--- a/beagle_board/scripts/front_shell_program
+++ b/beagle_board/scripts/front_shell_program
@@ -1,28 +1,96 @@
 #!/bin/bash
 
 NAME=`basename $0`
-DEV=/dev/i2c-1
-ADDR=0x15
+
+# Script written to monitor and control the DATA robot by Sawyer Larkin
+
+NAME=`basename $0`
 
 display_usage() { 
-  echo "Usage: $NAME file"
-  echo -e "   file - name of the hex file to upload to the BeagleBoard Trainer via I2C"
+  echo "Usage: $NAME [options] file" 1>&2
+  echo "" 1>&2
+	echo "Uploads a hex file to the Front Shell 328p on the DATA robot, via I2C." 1>&2
+  echo "" 1>&2
+	echo "If no I2C setup options are specified they will attempt to be set" 1>&2
+	echo "by environment variables:" 1>&2
+	echo "DATA_BASE_I2C_DEV and DATA_FRONT_I2C_BL_ADDR" 1>&2
+	echo "" 1>&2
+  echo "  file  Name of the file to upload" 1>&2
+  echo "  -a    I2C board address" 1>&2
+  echo "  -d    I2C device name" 1>&2
+  echo "  -h    Print this message" 1>&2
+  exit 1
 } 
+
+INVALID=INVALID
+VERBOSE=0
+
+DEV=${DATA_BASE_I2C_DEV:-$INVALID}
+ADDR=${DATA_FRONT_I2C_BL_ADDR:-$INVALID}
+
+while getopts "a:d:hv" opt
+do
+  case ${opt} in
+    a )
+      ADDR=$OPTARG
+      ;;
+    d )
+      DEV=$OPTARG
+      ;;
+    h )
+      display_usage
+      ;;
+    v )
+      VERBOSE=1
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      display_usage
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      display_usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
 
 if [[ $# -ne 1 ]]
 then
-  echo Error: incorrect number of arguments!
+  echo "Error: incorrect number of arguments! Please specify the file to write."
   display_usage
   exit 1
 fi
 
-if [[ ! -f $1 ]]
+FILE=$1
+
+if [[ ! -f $FILE ]]
 then
-  echo Error: $1 is not a file!
+  echo "Error: $FILE is not a file!"
   display_usage
-  exit 1
+fi
+
+if ! [[ $ADDR =~ ^[0-9xXaAbBcCdDeEfF]+$ ]]
+then
+  echo "No valid I2C board address specified!" 1>&2
+  echo "I2C Board Address: $ADDR" 1>&2
+  display_usage
+fi
+
+if [[ $DEV = $INVALID ]]
+then
+  echo "No valid I2C bus device specified!" 1>&2
+  echo "I2C Bus Device: $DEV" 1>&2
+  display_usage
+fi
+
+if [[ VERBOSE -ne 0 ]]
+then
+  echo "I2C Device Name:   $DEV"
+  echo "I2C Board Address: $ADDR"
+  echo "Filename: $FILE"
 fi
 
 shell_reset
 
-twiboot -d $DEV -a $ADDR -p1 -w flash:$1
+twiboot -d $DEV -a $ADDR -p1 -w flash:$FILE
